services:
  speech-to-phrase:
    build:
      context: .
      args:
        - BUILD_FROM=ghcr.io/home-assistant/amd64-base-debian:bookworm
        - ARCH=amd64
        - SPEECH_TO_PHRASE_VERSION=1.2.0 # check latest version and change if needed
    container_name: speech-to-phrase
    working_dir: /usr/src
    command: bash -c ".venv/bin/python3 -m speech_to_phrase  --uri
      'tcp://0.0.0.0:10300'  --tools-dir /usr/src/tools  --train-dir
      /data/train  --models-dir /data/models  --custom-sentences-dir
      /data/custom_sentences
      --retrain-on-start  --retrain-on-connect  --retrain-seconds
      300  --hass-token ${hass_token} --hass-websocket-uri
      ${hass_websocket_uri}"
    restart: unless-stopped
    user: 1000:1000 # change to your preferred non-root user
    ports:
      - 10300:10300
    volumes:
      - type: bind
        source: ${apps_storage}/models # make sure your user can write to this
        target: /data/models
      - type: bind
        source: ${apps_storage}/train # make sure your user can write to this
        target: /data/train
      - type: bind
        source: ${apps_storage}/custom-sentences
        target: /data/custom_sentences
networks: {}
